name: Build and Test Java App

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build-test:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up JDK 21
     uses: actions/setup-java@v4
     with:
       distribution: 'temurin'
       java-version: '21'

   - name: Generate version
     id: version
     run: |
       VERSION="1.0.${{ github.run_number }}"
       echo "version=$VERSION" >> $GITHUB_OUTPUT
       echo "Generated version: $VERSION"

   - name: Build and Test with Maven
     run: mvn clean package -DskipTests=false

   - name: Rename JAR with version
     run: |
       cp target/ecommerce-app-1.0-SNAPSHOT.jar target/ecommerce-app-${{ steps.version.outputs.version }}.jar

   - name: Upload JAR as artifact
     uses: actions/upload-artifact@v4
     with:
       name: ecommerce-app-${{ steps.version.outputs.version }}
       path: target/ecommerce-app-${{ steps.version.outputs.version }}.jar
       retention-days: 30

